@DTBC.Ludotek.Web.Api.UI_HostAddress = https://localhost:7200

GET {{DTBC.Ludotek.Web.Api.UI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DTBC.Ludotek.Web.Api.UI_HostAddress}}/api/persons

###

GET {{DTBC.Ludotek.Web.Api.UI_HostAddress}}/api/persons/default

###
